# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Javadocs

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B javadoc:javadoc --file watercore-api/pom.xml
    - uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: watercore-api/target/site/apidocs
        fqdn: gh.redaam.net
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
